version: "3.3"


services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    command:
      --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    ports:
      - '3306:3306'
    networks:
      - mynet
  myphp:
    image: php:7.4-fpm
    command: sh -c "docker-php-ext-install mysqli && docker-php-ext-enable mysqli && php-fpm"
    restart: always
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    networks:
      - mynet
  mynginx:
    image: nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - myphp
    volumes:
      - ./src:/var/www/html
      - ./src/nginx.ini:/etc/nginx/conf.d
    networks:
      - mynet
  phpMyAdmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      NGINX_HOST: mysql
      NGINX_PORT: 3306
    networks:
      - mynet
networks:
  mynet:
    driver: bridge