version: "3.3"


services:
  mydb:
    platform: linux/x86_64
    image: mysql:8
    restart: always
    environment:
#      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
#    command:
#      --init-file /data/application/init.sql
#    volumes:
#      - ./init.sql:/data/application/init.sql
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
  myphp:
    image: php:7.4-fpm
    command: sh -c "docker-php-ext-install mysqli && docker-php-ext-enable mysqli && php-fpm"
    restart: always
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mydb
    ports:
      - "9000:9000"
  mynginx:
    image: nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - myphp
      - mydb
    volumes:
      - ./src:/var/www/html
      - ./src/nginx.ini:/etc/nginx/conf.d/default.conf
  phpMyAdmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      NGINX_HOST: mydb
      NGINX_PORT: 3306
    depends_on:
      - mydb